version: '2'

services:
  postgres:
    restart: always
    build: ./postgres
    networks:
      - wc_n
    ports:
      - "5432:5432"

  web:
    restart: always
    build: .
    volumes:
      - .:/opt/apps/wordcount
    networks:
      - wc_n
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://wc_tutorial:wc_tutorial@postgres:5432/wordcount_dev
    depends_on:
      - postgres

networks:
    wc_n:
      driver: bridge
