version: '2'

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/opt/apps/wordcount
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  data:
    restart: always
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgres
    volumes_from:
      - data
    #expose:
    #  - "5432"
    ports:
       - "5432:5432"
